<?php
declare(strict_types=1);

// Maintains a generated route inventory inside the hand-authored OpenAPI file.
// The schemas remain intentionally hand-written; this catches route drift
// without adding a YAML dependency to the CMS.
$root = dirname(__DIR__);
$target = $root . '/docs/openapi-v1.yaml';
$routes = [
    '/articles' => ['GET', 'POST'], '/articles/{id}' => ['GET', 'PATCH', 'PUT', 'DELETE'],
    '/pages' => ['GET', 'POST'], '/pages/{id}' => ['GET', 'PATCH', 'PUT', 'DELETE'],
    '/media' => ['GET', 'POST'], '/media/{id}' => ['GET', 'DELETE'],
    '/listings' => ['GET', 'POST'], '/listings/{id}' => ['GET', 'PATCH', 'PUT', 'DELETE'],
    '/comments' => ['GET'], '/comments/{id}' => ['PATCH'],
    '/taxonomies' => ['GET', 'POST'], '/taxonomies/{id}' => ['PATCH', 'PUT', 'DELETE'],
    '/collections' => ['GET', 'POST'], '/collections/{id}' => ['GET', 'PATCH', 'PUT', 'DELETE'],
];
$inventory = "# BEGIN GENERATED ROUTE INVENTORY\n# This block is generated by php tools/generate_openapi.php.\n";
foreach ($routes as $path => $methods) {
    $inventory .= '# ' . implode(', ', $methods) . ' ' . $path . "\n";
}
$inventory .= "# END GENERATED ROUTE INVENTORY\n";
$current = file_get_contents($target);
if ($current === false) {
    fwrite(STDERR, "OpenAPI file not found.\n");
    exit(1);
}
if (preg_match('/# BEGIN GENERATED ROUTE INVENTORY.*# END GENERATED ROUTE INVENTORY\n?/s', $current)) {
    $next = preg_replace('/# BEGIN GENERATED ROUTE INVENTORY.*# END GENERATED ROUTE INVENTORY\n?/s', $inventory, $current);
} else {
    $next = rtrim($current) . "\n\n" . $inventory;
}
if (($argv[1] ?? '') === '--check') {
    if ($next !== $current) {
        fwrite(STDERR, "OpenAPI generated route inventory is stale. Run php tools/generate_openapi.php\n");
        exit(1);
    }
    echo "OpenAPI generated route inventory is current.\n";
    exit(0);
}
file_put_contents($target, $next);
echo "Updated docs/openapi-v1.yaml generated route inventory.\n";
